#!/config/workspace/Chatbot_GPT_3.5_Turbo/chatenv/bin/python3.7
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
